[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "DqRqXYZvkZ23E1bg2oMsYHX4mnA8E3xG55J9XjwiFgWC"

[programs.devnet]
solana_nft_anchor = "DqRqXYZvkZ23E1bg2oMsYHX4mnA8E3xG55J9XjwiFgWC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/user/my-solana-wallet/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
